"""empty message

Revision ID: 0930146fde8d
Revises: 
Create Date: 2019-12-16 18:21:37.512779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0930146fde8d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "foo_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("foo_model")
    # ### end Alembic commands ###
